spring:
  application:
    name: 'todo-app'
  h2.console:
    enabled: false
  datasource:
    url: 'jdbc:h2:file:./todo-db'
  jpa:
    hibernate:
      ddl-auto: create-drop
task.template.allowMultipleTasks: false