spring:
  application:
    name: 'todo-app'
  h2.console:
    enabled: true
    path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:./todo-db'
  jpa:
    hibernate:
      ddl-auto: create-drop
task.allowMultipleTasksFromTemplate: false