spring:
  application:
    name: 'todo-app'
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
task.template.allowMultipleTasks: false